version: "3.9"
services:
  postgres:
    container_name: apn-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5439:5432"

  pgadmin:
    container_name: apn-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5059:80"

  frontend:
    build:
      context: ..
      dockerfile: ./apn-frontend/Dockerfile
    container_name: apn-frontend
    restart: always
    ports:
      - "80:80"

  bff:
    build:
      context: ..
      dockerfile: ./apn-data-processor/Dockerfile
    container_name: apn-bff
    restart: always
    ports:
      - "3000:3000"

volumes:
  pgdata:
